name: Docker Image CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: set up jdk 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: build with maven
        run: mvn -B clean install -P pre-release -Djavacpp.platform=linux-x86_64

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          load: true
          tags: |
            workwithprashant/docker-zalenium:${{ env.VERSION }}
            workwithprashant/docker-zalenium:latest
            workwithprashant/docker-zalenium:latest-rc
      - name: Push Docker images
        run: docker push workwithprashant/docker-zalenium:latest-rc
      - name: Release image
        # Release image on 'main'
        if: github.ref == 'refs/heads/main'
        run: |
          docker push workwithprashant/docker-zalenium:latest
          docker push workwithprashant/docker-zalenium:${{ env.VERSION }}
